# Generated by Django 5.2.7 on 2025-11-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo_referido_cliente_referido_por'),
        ('fidelizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('meta', models.PositiveIntegerField(help_text='Ej: 5 canjes, 5000 puntos')),
                ('tipo', models.CharField(choices=[('CANJES', 'Cantidad de canjes'), ('PUNTOS', 'Puntos acumulados')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('icono', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_requeridos', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('MULTIPLICADOR', 'Multiplicador'), ('BONUS', 'Bonus fijo')], max_length=20)),
                ('valor', models.PositiveIntegerField(help_text='Ej: multiplicador 2 = 2x, bonus 100 = 100 puntos')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntos_utilizados', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.productocanje')),
            ],
        ),
        migrations.CreateModel(
            name='CanjeDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_utilizados', models.PositiveIntegerField()),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.bolsapuntos')),
                ('canje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.canje')),
            ],
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referido_email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bonus_otorgado', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_programa', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DesafioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='clientes.cliente')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.desafio')),
            ],
            options={
                'unique_together': {('cliente', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='InsigniaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='clientes.cliente')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.insignia')),
            ],
            options={
                'unique_together': {('cliente', 'insignia')},
            },
        ),
    ]
