# Generated by Django 5.2.7 on 2025-11-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        # Campo REAL correcto — SOLO UNA VEZ
        migrations.AddField(
            model_name='cliente',
            name='codigo_referido',
            field=models.CharField(max_length=20, unique=True, blank=True, null=True),
        ),

        migrations.AddField(
            model_name='cliente',
            name='referido_por',
            field=models.ForeignKey(
                related_name='referidos_por_cliente',
                to='clientes.cliente',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL
            ),
        ),

        # Generar códigos válidos únicos de max 20 chars
        migrations.RunSQL(
            sql="""
                UPDATE clientes_cliente
                SET codigo_referido = substring(md5(random()::text) from 1 for 20)
                WHERE codigo_referido IS NULL OR codigo_referido = '';
            """,
            reverse_sql="UPDATE clientes_cliente SET codigo_referido = NULL;"
        ),
    ]
