# Generated by Django 5.2.7 on 2025-11-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo_referido_cliente_referido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_referido',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
