# Generated by Django 5.2.7 on 2025-11-03 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('puntos_requeridos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Concepto de Puntos',
                'verbose_name_plural': 'Conceptos de Puntos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParametrizacionVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_duracion', models.PositiveIntegerField(default=365)),
            ],
            options={
                'verbose_name': 'Parametrización de Vencimiento',
                'verbose_name_plural': 'Parametrizaciones de Vencimiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_por_punto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Regla de Puntos',
                'verbose_name_plural': 'Reglas de Puntos',
                'ordering': ['limite_inferior'],
            },
        ),
        migrations.CreateModel(
            name='BolsaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateTimeField()),
                ('puntos_asignados', models.PositiveIntegerField(default=0)),
                ('puntos_utilizados', models.PositiveIntegerField(default=0)),
                ('monto_operacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Bolsa de Puntos',
                'verbose_name_plural': 'Bolsas de Puntos',
                'ordering': ['fecha_caducidad'],
            },
        ),
        migrations.CreateModel(
            name='UsoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_utilizados', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='clientes.cliente')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.conceptopuntos')),
            ],
            options={
                'verbose_name': 'Uso de Puntos',
                'verbose_name_plural': 'Usos de Puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UsoPuntosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_utilizados', models.PositiveIntegerField(default=0)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.bolsapuntos')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.usopuntos')),
            ],
            options={
                'verbose_name': 'Detalle de Uso de Puntos',
                'verbose_name_plural': 'Detalles de Uso de Puntos',
                'ordering': ['uso_id'],
            },
        ),
    ]
