# Generated by Django 5.2.7 on 2025-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(default='CI', max_length=30)),
                ('nacionalidad', models.CharField(default='Paraguaya', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel_fidelizacion', models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('DIAMANTE', 'Diamante')], default='BRONCE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
